"""Initial commit

Revision ID: 4618fbdb2288
Revises: 95c8f894c546
Create Date: 2024-10-13 22:42:59.770693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4618fbdb2288'
down_revision = '95c8f894c546'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
